Initial custom search and replace changes
git-svn-id: http://fnx.fnxweb.co.uk/repos/fnx/urllink/trunk@793 5a3ab4dc-b762-4687-8486-9e4b0467cd83

diff --git a/zip-rel b/zip-rel
--- a/zip-rel
+++ b/zip-rel
@@ -1,2 +1,9 @@
 #!/bin/bash
-zip -vrX9 ../urllink.xpi `find . -type f | grep -v '\.svn'`
+installver=$(grep em:version install.rdf | sed -e 's/^.*version>\(.*\)<.*/\1/')
+configver=$(grep version\ : ../src/content/urllinkCommon.js | sed -e 's/^.*version : "\(.*\)".*/\1/')
+if [ $installver != "$configver" ];  then
+    echo "ERROR: versions mismatch in ../src/content/urllinkCommon.js ($configver) and install.rdf ($installver)"
+    exit 1
+else
+    zip -vrX9 ../urllink.xpi $(find . -type f | grep -v '\.svn')
+fi
